/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SplashScreen.java
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author user
 */
public class SplashScreen extends javax.swing.JDialog {

    Timer tm;

    public SplashScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setAlwaysOnTop(true);
        setTitle("Weeraketiya Central College");
        setIconImage(new ImageIcon("./img/apple.png").getImage());
        this.setLocationRelativeTo(getRootPane());
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        SplashLabel.setIcon(new ImageIcon("./img/SplashFull.png"));
        tm = new javax.swing.Timer(100, new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                Properties sProp = java.lang.System.getProperties();
                SplashProgressBar.setValue(SplashProgressBar.getValue() + 1);
                if (SplashProgressBar.getValue() == 10) {
                    spLabel.setText("Checking JavaRuntime ....                   " + sProp.getProperty("java.version") + " found...");
                }
                if (SplashProgressBar.getValue() == 20) {
                    spLabel.setText("Checking Memory ....");
                }
                if (SplashProgressBar.getValue() == 25) {
                    spLabel.setText("Checking Config File .... ");
                }
                String xmlPath = "./configValues.xml";
                File file = new File(xmlPath);
                if (SplashProgressBar.getValue() == 30) {
                    if (!file.exists()) {
                        spLabel.setText("Configuration File Not available - Program Terminates..");
                    } else {
                        spLabel.setText("Configuration File Available ......");
                    }
                }
                if (SplashProgressBar.getValue() == 43 && !file.exists()) {
                    System.exit(0);
                }

                if (SplashProgressBar.getValue() == 50) {
                    spLabel.setText("Checking OS ....           " + sProp.getProperty("os.name") + "    found......");
                }
                if (SplashProgressBar.getValue() == 70) {
                    InetAddress thisIp = null;
                    try {
                        thisIp = InetAddress.getLocalHost();
                    } catch (UnknownHostException ex) {
                        Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    spLabel.setText("Checking IP ....                      " + thisIp.getHostAddress());
                }

                if (SplashProgressBar.getValue() == 95) {
                    spLabel.setText("Finalising...");
                }
                if (SplashProgressBar.getValue() == 100) {
                    tm.stop();
                    dispose();
                    new LogonFrame().setVisible(true);
                }

            }
        });
        tm.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplashLabel = new javax.swing.JLabel();
        SplashProgressBar = new javax.swing.JProgressBar();
        spLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Splash");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(SplashLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 250));
        getContentPane().add(SplashProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 298, 661, 20));

        spLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spLabel.setText("Initializing...");
        getContentPane().add(spLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 272, 542, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\Working Directory\\UCSC\\java\\Final Project - Andrew - 763052222V\\Net Beans\\StdAdmin\\img\\animate.gif")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 254, 150, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                SplashScreen dialog = new SplashScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SplashLabel;
    private javax.swing.JProgressBar SplashProgressBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel spLabel;
    // End of variables declaration//GEN-END:variables
}
